### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by AhmiDarrow** [ObliqueNET/Terra#225] opened 2019-04-14 17:41 UTC
Yes I had been banned previously As AhmiDarrow, and my wife was as R1s1ka as we gave away our items when we quit due to a change that happened about a year ago on Terra. With the gen 7 being released we came to check it out, were unbanned, I even messaged Ras on discord to apologize for our behavior previously as I did not want to be a hypocrite.  Upon trying to log in today our ORIGINAL ban is now back. Not sure why. Could we overturn this please?

**Comment by Rasgnarok** [comment] 2019-04-14 18:53
Hi! We recently swapped some old files around, so there is a possiblity of a simple mistake on our end. Can you please give me your discord username too?

**Comment by AhmiDarrow** [comment] 2019-04-14 19:29
Yes Ahmi#8070 and Risika#7218 are the discord names ahmidarrow & r1s1ka are the minecraft names

**Comment by Rasgnarok** [comment] 2019-04-14 21:43
![image](https://user-images.githubusercontent.com/18584380/56099549-7c231200-5edc-11e9-8229-f6b4a12ad9c4.png)
Ah, that's you. Well I didn't know who you were, which is why I had replied this. As far as I can find, I did not issue an unban - you could be confusing the hub with Terra, which does not have synced ban lists, therefore allowing you to join the network but not the server. Did you ever make a ban appeal?

**Comment by AhmiDarrow** [comment] 2019-04-14 23:44
Just this one as when we heard about the update we downloaded the reforged from Technic, saw Oblique and figured we'd try. Logged into the lobby and then went to Terra. We were reset character data wise, still married though. Played for maybe an hour then when we went to log in today we were banned with the original message.

**Comment by AhmiDarrow** [comment] 2019-04-14 23:46
Never seeking the repeal of the original ban is why I sent the apology to you before I felt comfortable playing this time around. I had no ill will and wanted to make make that clear.

**Comment by R1s1ka** [comment] 2019-04-15 22:02
Hi! This is R1s1ka, I just wanted to apologize as well. My actions were unnecessary, ignorant, and unkind. I do sincerely apologize for this. 

Do to however we were able to get in, failure of the ban transferring when the  update went through or something, I dunno... When I first logged in, I saw that I could choose a pokemon, logged back out, the logged back in and chose a Litten. :) I did get to see the work that had been done to the spawn area. I was so confused at first, the tree spawn was gone. It was all flat and open, then my screen said 'Welcome to Arvandor' and I was like 'YAY!'

I do miss playing minecraft, I do miss catching pokes, but most of all I do miss playing on Oblique, is there anyway we could get the ban removed? I do understand if you choose to keep it. 

You have an awesome server, have to keep it awesome. I do understand that. :)

**Comment by Rasgnarok** [comment] 2019-04-15 22:31
Can you remember the causes for the unban? As for the ban 'coming back', its more of a woopsie on my end - bans were erased when I first did the reset, because I reset the player data. However, on second login, it likely has re-synced now with the files I added back. Anyways, let's proceed with a ban appeal.

**Comment by AhmiDarrow** [comment] 2019-04-16 00:13
What information is needed from us to proceed with that?

**Comment by Rasgnarok** [comment] 2019-04-16 01:39
Just the circumstances of it, I am trying to get your point of view from the ban

**Comment by AhmiDarrow** [comment] 2019-04-16 01:53
Well we were banned for giving away our items when the GTS was taken out because the primary way we made our living as pixelmon breeders(the playstyle we love and reason we love pixelmon)was selling all of our stock on the GTS. However I do want to mention the ban message said "please don't ruin our economy" and I afterwards saw a message from you on discord saying the same. 
  The giving away of our items was NOT in any way meant to be malicious in nature. Had I seen the discord message before the ban I would have stopped and simply logged out and left it at that. Again I was never trying to cause harm, simply mad that I couldn't play the way I had spent over 300 to 400 hours of in game time doing, and if I wasn't going to use all the hard work I thought someone should benefit. 
  I hadn't thought of it again until we saw all the updates about reforged and upon installing Oblique was right at the top so we thought we would check it out, it always has and assumed would be the best out there. If we are able to come play again I would be very appreciative.

**Comment by Rasgnarok** [comment] 2019-04-16 01:57
I'll unban you and your wife, but in the future, just remember that there doesn't need to be drastic measures if you just communicate. All decisions have reasons. You are now both unbanned.

**Closed by Rasgnarok** 2019-04-16 01:57 UTC
Labels: admin

**Comment by AhmiDarrow** [comment] 2019-04-16 02:02
Thank you Ras I appreciate it.
