### ISSUE TITLE
Problem with the new claim plugin for Vanha

### ISSUE THREAD

**Issue by TSaulio** [ObliqueNET/Terra#191] opened 2019-02-19 23:44 UTC
This bug happened in the other plugin aswell but now is even worse, it happens that you can break armor stands with a bow. If the players find this they can take advantage of it and steal the armors in the adventure map.
  I know it happened with the other plugin and tried to see if it was fixed but now is even worse since before you could put the armor stand back if you broke it by accident but now you can't.
 I tested it and, yes it happens with item frames aswell, and since there are medals in the gyms, players can take them and that could be a major problem.

PD: I retrieved the armor and the medal I got to a mod, who put them back in it's place.

**Comment by ElementalMP** [comment] 2019-02-27 06:55
Confirmed as of the current version.

**Comment by Vohras2** [comment] 2019-04-15 01:01
Confirmed still happens post reset.

**Comment by Hiroku** [comment] 2019-04-15 09:32
Should be fixed with the next code update

**Comment by Vohras2** [comment] 2019-06-26 21:26
Closing since Roku says it is fixed.

**Closed by Vohras2** 2019-06-26 21:26 UTC
Labels: bug, landlord
