### ISSUE TITLE
Breeding speeds in filled ranch.

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#89] opened 2018-04-13 03:22 UTC
I have a ranch with 3 sets of water1 Pokemon. Lapras/Froakie, Froakie/Froakie, and Psyduck/Froakie. All in a single ranch in a breeding zone with full tier3 blocks. The first two breed at the expected speed, but the 3rd group always lags behind by several minutes.

**Comment by Rasgnarok** [comment] 2018-04-24 22:30
Not a bug, closing.

**Closed by Rasgnarok** 2018-04-24 22:30 UTC
