### ISSUE TITLE
Pokemon not evolving

### ISSUE THREAD

**Issue by ElementalMP** [ObliqueNET/Terra#105] opened 2018-06-18 00:20 UTC
Pokemon will sometimes not evolve for some reason, even after requirements have been greatly exceeded. Pselling the Pokémon to another player then leveling it up will evolve the Pokemon.

**Comment by Rasgnarok** [comment] 2018-07-01 21:41
I'd need a consistent way of reproducing this. Has anyone managed to do that?

**Comment by ElementalMP** [comment] 2018-07-02 21:04
Not that I know of. The issue is fairly uncommon now, not sure if it was patched. The problem with investigating the bug, is that if they give you the mon to look at, it fixes the bug.

**Comment by TeslaPyro** [comment] 2018-09-13 18:02
I've had this issue a few times. The few times it has happened have been a result of the pokemon being over the evolution level when caught in the wild. As of right now I believe I caught a koffing at level 35-36, and it has gotten up to lvl 49 with no evolution.

**Comment by Vohras2** [comment] 2019-06-16 04:32
Closing this since it is old.

**Closed by Vohras2** 2019-06-16 04:32 UTC
Labels: needs testing, pixelmon
